[tool.kedro]
package_name = "text_classification"
project_name = "text-classification"
kedro_init_version = "0.18.12"

[tool.isort]
profile = "black"
extend_skip = [".ipython", ".git", "env", ".github"]

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--ignore src/tests/tests_regression/ \
--cov src/text_classification -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
