data_preparation:
  test_size: 0.2
  max_num_samples_per_class: 1000
  random_state: 0

model_training:
  vectorizer_parameters:
    stop_words: "english"
    max_df: 0.75
    min_df: 0.00 
    max_features: 7000
    binary: False
    use_idf: True 
    norm: "l2"
  classifier_parameters:
    n_estimators: 15
    max_depth: 5
    learning_rate: 0.3
    subsample: 1
    colsample_bytree: 1
    colsample_bylevel: 1
    colsample_bynode: 1
    reg_lambda: 0.5
    reg_alpha: 0
    seed: 0

model_prediction:
  id: "0000"
  narrative: "Any test text to classify."

model_serving:
  title: "Text-Classifier" 
  host: "0.0.0.0"
  port: 7860