name: Application Checking

on:
  pull_request:
    branches: [ main ]

jobs:

  build_image:
    name: Image Building
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS_PATH: "./src/requirements.in"
      ENTRYPOINT_PATH: "./entrypoint.sh"
      DOCKERFILE_PATH: "Dockerfile"
      DOCKERIMAGE_NAME: "classifier_app"
    steps:
      
      - name: Check out the code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build --build-arg REQUIREMENTS_PATH=$REQUIREMENTS_PATH --build-arg ENTRYPOINT_PATH=$ENTRYPOINT_PATH  -t $DOCKERIMAGE_NAME -f $DOCKERFILE_PATH .
    
      - name: Unitary Tests (Functions)
        run: |
          docker run --rm --entrypoint "pytest" $DOCKERIMAGE_NAME src/tests/tests_unitary/