name: CI/CD/CT Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  ci_cd_ct:
    name: Prediction Service Deployment
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS_PATH: "./src/requirements.in"
      ENTRYPOINT_PATH: "./entrypoint.sh"
      DOCKERFILE_PATH: "Dockerfile"
      DOCKERIMAGE_NAME: "classifier_app"

    steps:
      
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5' 

      - name: Install requirements
        run: |
          pip install requirement.txt

      - name: Train ML model
        run: |
          kedro run --pipeline training
      
      - name: Build Docker image
        run: |
          docker build --build-arg REQUIREMENTS_PATH=$REQUIREMENTS_PATH --build-arg ENTRYPOINT_PATH=$ENTRYPOINT_PATH  -t $DOCKERIMAGE_NAME -f $DOCKERFILE_PATH .

      - name: Check all tests
        run: |
          docker run --rm --entrypoint "pytest" $DOCKERIMAGE_NAME -v .
