name: CI/CD/CT Workflow

on:
  pull_request:
    branches: [ main ]

jobs:

  ci_cd_ct:
    name: Prediction Service Deployment
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS_PATH: "./src/requirements.in"
      ENTRYPOINT_PATH: "./entrypoint.sh"
      DOCKERFILE_PATH: "Dockerfile"
      DOCKERIMAGE_NAME: "classifier_app"
    steps:
      
      - name: Check out the code
        uses: actions/checkout@v4.0.0

      - name: Print working directory
        run: pwd

      - name: Print current directory content
        run: ls -R

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5' 
      
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install --quiet --requirement src/requirements.in
          pip install -e src/.

      - name: Train ML model
        run: |
          kedro run --conf-source=/home/runner/work/text-classification/text-classification/conf --pipeline training

      - name: Build Docker image
        run: |
          docker build --build-arg REQUIREMENTS_PATH=$REQUIREMENTS_PATH --build-arg ENTRYPOINT_PATH=$ENTRYPOINT_PATH  -t $DOCKERIMAGE_NAME -f $DOCKERFILE_PATH .
    
      - name: Check all tests
        run: |
          docker run --rm --entrypoint "pytest" $DOCKERIMAGE_NAME -v .

