name: CI/CD/CT Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  ci_cd_ct:
    name: Prediction Service Deployment
    runs-on: windows-latest
    env:
      REQUIREMENTS_PATH: "./src/requirements.in"
      ENTRYPOINT_PATH: "./entrypoint.sh"
      DOCKERFILE_PATH: "Dockerfile"
      DOCKERIMAGE_NAME: "classifier_app"

    steps:
      
      - name: Check out the code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build --build-arg REQUIREMENTS_PATH=$REQUIREMENTS_PATH --build-arg ENTRYPOINT_PATH=$ENTRYPOINT_PATH  -t $DOCKERIMAGE_NAME -f $DOCKERFILE_PATH .
    
      - name: Train ML model
        run: |
          docker run --rm --entrypoint "kedro" $DOCKERIMAGE_NAME run --pipeline training

      - name: Check all tests
        run: |
          docker run --rm --entrypoint "pytest" $DOCKERIMAGE_NAME -v .
