name: CI/CD/CT Workflow

on:
  pull_request:
    branches: [ main ]

jobs:

  ci_cd_ct:
    name: Prediction Service Deployment
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out the code
        uses: actions/checkout@v4.0.0

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5' 

      - name: Print current directory content
        run: ls -R

      - name: Build Docker image
        env:
          REQUIREMENTS_PATH: "./src/requirements.in"
          ENTRYPOINT_PATH: "./entrypoint.sh"
          DOCKERFILE_PATH: "Dockerfile"
          DOCKERIMAGE_NAME: "classifier_app"
        run: |
          docker build --build-arg REQUIREMENTS_PATH=$REQUIREMENTS_PATH --build-arg ENTRYPOINT_PATH=$ENTRYPOINT_PATH  -t $DOCKERIMAGE_NAME -f $DOCKERFILE_PATH .
    
      - name: Print current directory content
        run: |
          docker run --entrypoint "ls" $DOCKERIMAGE_NAME -R

      - name: Check all tests
        run: |
          docker run --rm --entrypoint "pytest" $DOCKERIMAGE_NAME -v .

      - name: Train the machine learning model
        run: |
          docker run --rm --entrypoint "kedro" $DOCKERIMAGE_NAME run --pipeline training
